"""Builds src/Title/topo.ts: real contour lines of the Oltrepò's mountains,
for the background of the series title.

The ground round Varzi, the Penice and the Lesima, 22 x 22 km, from the
public Terrarium elevation tiles (AWS Open Data, "elevation-tiles-prod"),
contoured every 100 m with every fifth line marked as an index contour, the
way a topographic map draws them.

    python3 scripts/geo/build_title_topo.py
"""
import io, math, os, ssl, sys, urllib.request

import numpy as np
from PIL import Image
from scipy import ndimage as ndi
from shapely.geometry import LineString
from skimage import measure

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_TS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "src", "Title", "topo.ts")
TILE = "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png"
Z = 12
BOX = (9.14, 44.70, 9.42, 44.90)   # lon0, lat0, lon1, lat1
SIZE = 1000                        # output viewBox, square
STEP, INDEX = 100, 500             # metres
PLACES = {"varzi": (9.1969, 44.82354), "penice": (9.3283, 44.79729)}


def tile_xy(lon, lat, z):
    n = 2 ** z
    x = (lon + 180) / 360 * n
    y = (1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2 * n
    return x, y


def fetch(z, x, y):
    ctx = ssl.create_default_context(cafile="/root/.ccr/ca-bundle.crt") \
        if os.path.exists("/root/.ccr/ca-bundle.crt") else None
    with urllib.request.urlopen(TILE.format(z=z, x=x, y=y), context=ctx, timeout=60) as r:
        rgb = np.asarray(Image.open(io.BytesIO(r.read())).convert("RGB")).astype(np.float64)
    return rgb[..., 0] * 256 + rgb[..., 1] + rgb[..., 2] / 256 - 32768


fx0, fy0 = tile_xy(BOX[0], BOX[3], Z)
fx1, fy1 = tile_xy(BOX[2], BOX[1], Z)
tx = range(int(fx0), int(fx1) + 1)
ty = range(int(fy0), int(fy1) + 1)
mosaic = np.vstack([np.hstack([fetch(Z, x, y) for x in tx]) for y in ty])
print(f"{len(tx)}x{len(ty)} tiles, elevation {mosaic.min():.0f}-{mosaic.max():.0f} m")

# Resample the box onto a square grid (over 22 km the Mercator stretch is
# negligible, and the projection is linear in lon and in y).
gx = np.linspace(fx0, fx1, SIZE) - tx[0]
gy = np.linspace(fy0, fy1, SIZE) - ty[0]
yy, xx = np.meshgrid(gy * 256, gx * 256, indexing="ij")
elev = ndi.map_coordinates(mosaic, [yy, xx], order=1)
elev = ndi.gaussian_filter(elev, 2.0)  # tile noise would fray the lines
print(f"box: {elev.min():.0f}-{elev.max():.0f} m")


def to_view(lon, lat):
    x, y = tile_xy(lon, lat, Z)
    return ((x - fx0) / (fx1 - fx0) * SIZE, (y - fy0) / (fy1 - fy0) * SIZE)


paths = []
for level in range(int(elev.min() // STEP + 1) * STEP, int(elev.max()) + 1, STEP):
    for c in measure.find_contours(elev, level):
        if len(c) < 30:
            continue
        line = LineString([(p[1], p[0]) for p in c]).simplify(1.2)
        if line.length < 40:
            continue
        d = "M" + "L".join(f"{x:.0f},{y:.0f}" for x, y in line.coords)
        paths.append((level, level % INDEX == 0, d))
print(f"{len(paths)} contour lines")

out = [
    "// Auto-generated by scripts/geo/build_title_topo.py - do not hand-edit.",
    "// Contours: Terrarium elevation tiles (AWS Open Data), every 100 m.",
    f"export const TOPO_SIZE = {SIZE};",
    "export const contours: { level: number; index: boolean; d: string }[] = [",
]
for level, idx, d in paths:
    out.append(f'  {{ level: {level}, index: {"true" if idx else "false"}, d: "{d}" }},')
out.append("];")
for name, ll in PLACES.items():
    x, y = to_view(*ll)
    out.append(f"export const {name.upper()} = {{ x: {x:.1f}, y: {y:.1f} }};")
out.append("")
os.makedirs(os.path.dirname(OUT_TS), exist_ok=True)
with open(OUT_TS, "w") as f:
    f.write("\n".join(out))
print("wrote", OUT_TS, os.path.getsize(OUT_TS), "bytes")
