"""Builds src/Title/titleShapes.ts: the shapes for the series title card.

Lombardia's outline (openpolis/ISTAT), and its south - the Oltrepò Pavese:
the comuni of the province of Pavia that lie south of the Po, the river
itself from OpenStreetMap via Overture Maps - plus a dot on Varzi, where
the films start. Everything is projected into a small square viewBox, the
same equirectangular projection as the maps, so the card's Lombardia is the
maps' Lombardia.

    python3 scripts/geo/build_title.py
"""
import json, math, os, sys

import pyarrow.dataset as ds
import shapely
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from overture_route import BUCKET, RELEASE, in_box, s3  # noqa: E402

OUT_TS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "src", "Title", "titleShapes.ts")
K = math.cos(math.radians(45.6))
VIEW = 400.0
VARZI = (9.1969, 44.82354)


def load(name):
    with open(os.path.join(HERE, name)) as f:
        return json.load(f)


regions = load("italy_regions.geojson")
lomb = next(shapely.geometry.shape(f["geometry"]) for f in regions["features"]
            if f["properties"]["reg_name"] == "Lombardia")

# The Po across the province of Pavia.
water = ds.dataset(f"{BUCKET}/release/{RELEASE}/theme=base/type=water/", filesystem=s3(), format="parquet")
po_parts = [shapely.from_wkb(r["geometry"]) for r in
            water.to_table(columns=["names", "class", "geometry"], filter=in_box((8.5, 44.95, 9.6, 45.25))).to_pylist()
            if r["class"] == "river" and ((r.get("names") or {}).get("primary") or "") in ("Po", "Fiume Po")]
po = unary_union([g for g in po_parts if g.geom_type in ("LineString", "MultiLineString")])
if po.is_empty:
    sys.exit("no Po in the water theme")
print(f"Po: {len(po_parts)} pieces, bounds {[round(v, 3) for v in po.bounds]}")


def po_lat_at(lon):
    """Latitude of the Po where it crosses this meridian (the southernmost
    crossing, so a meander never pulls a south-bank comune north)."""
    cut = po.intersection(shapely.geometry.LineString([(lon, 44.5), (lon, 45.6)]))
    ys = [p.y for p in getattr(cut, "geoms", [cut]) if not p.is_empty and p.geom_type == "Point"]
    return min(ys) if ys else None


comuni = load("limits_IT_municipalities.geojson")
south = []
for f in comuni["features"]:
    if f["properties"].get("prov_acr") != "PV":
        continue
    g = shapely.geometry.shape(f["geometry"])
    c = g.representative_point()
    lat = po_lat_at(c.x)
    if lat is not None and c.y < lat:
        south.append(g)
oltrepo = unary_union(south).buffer(0.002).buffer(-0.002)
print(f"Oltrepò Pavese: {len(south)} comuni")
if not oltrepo.contains(shapely.geometry.Point(VARZI)):
    sys.exit("Varzi is not in the Oltrepò shape")

x0, y0, x1, y1 = lomb.bounds
span = max((x1 - x0) * K, y1 - y0)
pad = 0.04 * VIEW
sc = (VIEW - 2 * pad) / span
ox = pad + ((VIEW - 2 * pad) - (x1 - x0) * K * sc) / 2
oy = pad + ((VIEW - 2 * pad) - (y1 - y0) * sc) / 2


def project(lon, lat):
    return (ox + (lon - x0) * K * sc, oy + (y1 - lat) * sc)


def path(geom, tol):
    geom = geom.simplify(tol)
    polys = [geom] if geom.geom_type == "Polygon" else sorted(geom.geoms, key=lambda p: -p.area)
    out = ""
    for p in polys:
        if p.area < 1e-4:
            continue
        pts = [project(*c) for c in p.exterior.coords]
        out += "M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z"
    return out


vx, vy = project(*VARZI)
lines = [
    "// Auto-generated by scripts/geo/build_title.py - do not hand-edit.",
    "// Lombardia: openpolis/ISTAT. Oltrepò Pavese: the comuni of PV south of the Po",
    "// (river: OpenStreetMap via Overture Maps).",
    f"export const VIEW = {VIEW:.0f};",
    f'export const LOMBARDIA = "{path(lomb, 0.004)}";',
    f'export const OLTREPO = "{path(oltrepo, 0.003)}";',
    f"export const VARZI = {{ x: {vx:.1f}, y: {vy:.1f} }};",
    "",
]
os.makedirs(os.path.dirname(OUT_TS), exist_ok=True)
with open(OUT_TS, "w") as f:
    f.write("\n".join(lines))
print("wrote", OUT_TS, os.path.getsize(OUT_TS), "bytes")
